server:
  port: 8200
spring:
  application:
    name: upload-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

mingrui:
  upload:
    path:
      windows: D:\mr\upload\img
      linux: /wsq/images
    img:
      host: http://image.mrshop.com